module.exports = {
    channels: {
        APP_INFO: 'app_info',
        CREATE_PROFILE: 'create_profile',
        UPDATE_PROFILE: 'update_profile',
        LOAD_PROFILE: 'load_profile',
        LOAD_KEBELE: 'load_kebele',
        CREATE_KEBELE: 'create_kebele',
        UPDATE_KEBELE: 'update_kebele',
        LOAD_GOTE: 'load_gote',
        CREATE_GOTE: 'create_gote',
        UPDATE_GOTE: 'update_gote',
        LOAD_ENROLLMENT_PERIOD: 'load_enrollment_period',
        CREATE_ENROLLMENT_PERIOD: 'create_enrollment_period',
        UPDATE_ENROLLMENT_PERIOD: 'update_enrollment_period',
        LOAD_MEMBER: 'load_member',
        LOAD_MEMBERS: 'load_members',
        CREATE_MEMBER: 'create_member',
        UPDATE_MEMBER: 'update_member',
        MEMBER_SUCCESS: 'member_success',
        SEND_NOTIFICATION: 'send_notification',
        DEV_TOOLS: 'dev_tools',
    },
    genderOptions: ['Male', 'Female'],
    relationshipOptions: ['Household Head', 'Parent', 'Husband', 'Wife', 'Son', 'Daughter', 'Other'],
    professionOptions: ['Farmer', 'Student'],
    administrativeLevelOptions: ['Kebele', 'Gote'],
    EthiopianMonths: ['Meskerem', 'Tikemt', 'Hidar', 'Tahesas', 'Tir', 'Yekatit', 'Megabit', 'Miyazia', 'Ginbot', 'Sene', 'Hamle', 'Nehase'],
};